# Generated by Django 5.2.11 on 2026-03-02 06:07

import apps.products.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.CharField(choices=[('NEW', 'Yangi'), ('PERFECT', 'Ideal'), ('GOOD', 'Yahshi'), ('NOT_BAD', 'Qoniqarli')], default='NEW', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[('STRICT', "Qat'iy"), ('AGREED', 'Kelishiladi'), ('FREE', 'Bepul'), ('EXCHANGE', 'Ayirboshlash')], default='AGREED', max_length=10)),
                ('region', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('favourite_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('MODERATION', 'Moderatsida'), ('ACTIVE', 'Aktiv'), ('REJECT', 'Rad etilgan'), ('SOLD', 'Sotilgan'), ('ARCHIVED', 'Arxivlangan')], default='MODERATION', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(default=apps.products.models.Product.default_expiry)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
