# Generated by Django 5.2.11 on 2026-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products/'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
