# Generated by Django 5.2.11 on 2026-03-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_num'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
